services:
  - type: web
    name: recipe-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL
    postdeployCommand: "python seed.py"
